### ISSUE TITLE
Collaborating with other groups

### ISSUE THREAD

**Issue by renepickhardt** [LNP-BP/LNPBPs#12]
Maybe it makes sense to talk to the Chris stewart from suredbits who has just started this repo: https://github.com/discreetlogcontracts/dlcspecs I think DLCs especially with respect to this issue https://github.com/discreetlogcontracts/dlcspecs/issues/3 are very relevant to RGB stuff

**Comment by dr-orlovsky** [comment]
It will be great to talk to them regarding this question. I know them in person, so will write and see what they will say
