### ISSUE TITLE
ticker doesn't allow numbers

### ISSUE THREAD

**Issue by zoedberg** [LNP-BP/LNPBPs#158]
After updating RGB crates to the latest master branches I'm no longer able to issue assets with a ticker containing numbers. When I try issuing an asset with ticker `TICKER2` I receive the following error: `identifier name 'TICKER2' contains invalid character '2'`

From the [spec](https://github.com/LNP-BP/LNPBPs/blob/master/lnpbp-0031.md) it seems ticker is defined as `AlphaCapsNum` so I think this is a regression.

@dr-orlovsky could you please clarify this?

**Comment by dr-orlovsky** [comment]
Can you pls move the issue to https://github.com/RGB-WG/rgb-wallet/issues where it belongs to? Since it is not a bug in the specification but in the implementation.

**Comment by zoedberg** [comment]
Sure, but I'm not able to move this so here the new issue: https://github.com/RGB-WG/rgb-wallet/issues/57
