### ISSUE TITLE
Add contract media global state

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/LNPBPs#161]
As a result of https://github.com/orgs/LNP-BP/discussions/160 it [was decided](https://github.com/orgs/LNP-BP/discussions/160#discussioncomment-6194335) to add unmodifiable and optional contract media global state to the RGB20 interface. I propose to combine it with `ContractText` into a new data type.

**Comment by zoedberg** [comment]
I guess we can close this now @dr-orlovsky

**Comment by dr-orlovsky** [comment]
Closed with https://github.com/LNP-BP/LNPBPs/pull/163
