### ISSUE TITLE
Replace complex ec operations with a hash in LNPBP-0004

### ISSUE THREAD

**Issue by afilini** [LNP-BP/LNPBPs#19]
The fifth step of LNPBP-0004 says that

> For each of the slots that remain empty (the slot number is represented by j):
>  * tweak public key R with it's own hash H(R) j times: Rj = R + J * H(R) * G)
>  * compute a 256-bit bitcoin hash of Rj and serialize it into the slot j using bitcoin-style hash serialization format.

Where `R` is `entropy * G`. 

I think we could replace that with a simple `SHA256(entropy || j)`

**Comment by dr-orlovsky** [comment]
My consideration: we need to force that the amount of entropy is sufficient. How we can enforce that the size of the hashed entropy would not be lees than some specific level?

**Comment by dr-orlovsky** [comment]
After the discussion on the today call it was decided to stick to simple deterministic hashes and do not use either EC math or verifiable delay functions
