### ISSUE TITLE
Filling asset Genesis metadata

### ISSUE THREAD

**Issue by UkolovaOlga** [LNP-BP/LNPBPs#35]
![Designing RGB smart contracts table](https://user-images.githubusercontent.com/22024706/85568661-285c9e80-b632-11ea-8850-bca5a61748cb.jpeg)

### Questions:
1. Is our table compliant with CA?
2. Do we need introduction of the timestamp?

**Comment by dr-orlovsky** [comment]
Closing as outdated with new asset schemas according to https://github.com/LNP-BP/LNPBPs/issues/44
