### ISSUE TITLE
Dust limit set up when filling Genesis metadata

### ISSUE THREAD

**Issue by UkolovaOlga** [LNP-BP/LNPBPs#36]
![Designing RGB smart contracts table](https://user-images.githubusercontent.com/22024706/85568429-f77c6980-b631-11ea-8ca7-e2886fcf56ea.jpeg)

### Questions:
1. Do we need to set it at all? 
2. Is it present in Confidential Assets?
3. What is the reasonable upper bound for “Dust limit” value?

**Comment by dr-orlovsky** [comment]
Decision from the last call: remove dust limit
