### ISSUE TITLE
Asset Pruning/Burning

### ISSUE THREAD

**Issue by UkolovaOlga** [LNP-BP/LNPBPs#38]
### Open questions:
1. Which term to use?
2. Do we need the ability to prohibit Burning/pruning?
3. Do we need to restrict burning rights to a single UTXO only?
4. Do we need to add proofs metadata to the pruning transaction?
6. Do we need to allow the removal or pruning rights at all?

### Possible Options: 
1. Disallow procedure for all RGB-20 fungible assets (remove from Schema).
2. Leave as is. 
3. Add ability to add custom (of many possible types) proofs Allow asset issuers to mark them required in Genesis.
4. Add epochs mechanism with eventual validation.
5. Combination of 3 & 4.

**Comment by dr-orlovsky** [comment]
Outdated by https://github.com/LNP-BP/rgb-node/pull/19
