### ISSUE TITLE
Restructuring asset-related RGB schemata

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/LNPBPs#44]
As was discussed during the dev call on 15th Jul 2020, use cases for different forms of tokens (stable coins, shares) will benefit from having separated schema. Here I propose to define the following set of schema for all asset-related cases:

1. Single-issuance fungible digital rights
   - non-inflatible
   - no burn procedure
2. Securities
   - inflatible
   - burn procedure
   - no reissuance after burning
3. Coins
   - inflatible
   - burn procedure
   - reissuance after the burn
4. Collectibles
   - unique
   - multiple issues in series
   - burnable?
   - rich metadata

All of these schemas will be proxied by a single `asset` RGB contract daemon (inside RGB node) with a single standard API for reducing the complexity of integration from a wallet perspective.

**Comment by dr-orlovsky** [comment]
After the call we have decided not to have the burn and history truncation procedures for initial collectible schema. For more complex cases, we will be designing more schemas with the time

**Comment by sabina-sa** [comment]
These is a feature that is quite popular with exchanges: “split” for stocks or “redenomination” for coins. Corporations like Apple often split their share so that it becomes more affordable, and I recall that Polkadot had a redenomination recently. “Split” or “redenomination” means that every holder of an asset gets an "airdop" of multiple assets of the same type, X. It looks like issuing new assets, but in reality it is not that, but instead it is a change in the way that the assets are counted, e.g. as if we switched from Bitcoins to Satoshis. Maybe we could implement it on RGB schemas, in a way that this is not confused with issuing new assets.

**Comment by dr-orlovsky** [comment]
The point of RGB is to have equation "once we reached agreement, some party can't change it without your consensus; even if the majority votes for it". So it's not a tech problem, but a governance problem: RGB have no governance after genesis; not even issuer or majority can decide. It is a feature.

**Comment by sabina-sa** [comment]
My worry is that absence of splits makes RGB less compatible with normal stock exchanges. "We can't do a stock split" - that might be an argument against listing stocks in parallel on RGB along with a normal stock exchange.

**Comment by dr-orlovsky** [comment]
Who will be taking decision? And how to avoid contradiction to the main principle "you can't force owners into something w/o their permission?"

Were there stock splits for bearer-right assets?

**Comment by dr-orlovsky** [comment]
What we can do, is that we can have a "split right", which will be defined at the level of asset issuance in genesis for shares schema, and use this right to perform a split action. This will complicate schema, but it will grant the issuer an option to define that right holders, and all those who will be owning assets will know about such possibility from the very beginning.

**Comment by dr-orlovsky** [comment]
@sabina-sa With https://github.com/LNP-BP/rgb-node/pull/19 I introduce "renomination" procedure which allows issuer (or a party defined by the issuer) to update all asset data, including:
- name
- contract (like text of contract, it's Ricardian representation or URL to it)
- precision, which will allow "splits" (if it was decreased) or "joins" (if it was increased)
