### ISSUE TITLE
Support for asset name registries

### ISSUE THREAD

**Issue by fedsten** [LNP-BP/LNPBPs#75]
In the [current schema structure](https://github.com/LNP-BP/rgb-node/blob/68146c578190bb578f2a4bf0f8d3298f94f0959a/src/contracts/fungible/data/schema.rs) there is a field `Name` for the asset, which however is not supposed to be unique. For a smoother user experience, it would be nice to have asset names that are unique and standardised across wallets, and for this purpose it would be useful to add support for asset name registries, similar to the [one used by Blockstream](https://assets.blockstream.info/) for Liquid.

To implement this I see two possible ways: (i) add in the schema a field for a URL pointer to an asset registry, where a trusted registry maintainer maps asset IDs with unique names, or (ii) add in the schema a field where it can be inserted a signature of a registry maintainer that certifies the unique name of the asset.

Obviously, then it will be up to wallet providers to decide which registry services to support and how to show different assets that may have the same name in different registries. This new field does not necessarily need to substitute the already existing `Name` field, as that could still be used as a name to show in a wallet user interface in the case the issuer did not subscribed to any registry service.

**Comment by dr-orlovsky** [comment]
Summary: after the discussing during dev call we have reviewed the difference between adding asset-related information to the genesis vs adding them to the registry. Registries will be based on Bifrost servers and there might be multiple registries; registry data are not global and different registries may provide  a different view on the same asset. Genesis-based data are global: the issuer commits to them and can't display two different genesis for different users/clients
