### ISSUE TITLE
Rename: LNP-BP is a misleading name/brand for this project.

### ISSUE THREAD

**Issue by msgilligan** [LNP-BP/lnpbps#9]
I suggest some renaming/rebranding of this project.

I really like the *idea* of a Bitcoin protocol stack modeled after TCP/IP. It is cool that LNP/BP has a very similar "ring" (sound) to TCP/IP.

But I think it is very confusing and misleading to *name* the set of specifications LNP/BP when the criteria for proposals is that they not be LNP or BP specifications.

I think the key word we are looking for might be protocol *stack* or protocol *suite*. Maybe someone like **BPStack** or **BPSuite**?

**Comment by dr-orlovsky** [comment]
Thanks for supporting LNP/BP idea modeled after TCP/IP. Let me explain the story behind the naming for the GitHub repos.

This GitHub organization (LNP-BP) is named after the LNP/BP Standards Association, which is a Swiss association operating under the article 60 of Swiss civil code and created to support the development of LNP/BP standards and their implementations — hence the name.

These standards _do_ cover both Bitcoin protocol itself and Lightning network protocol; in particular LNPBP1-4 are directly related to Bitcoin protocol layer. We also plan to work on a refactoring of BOLTs standard in a more formal way as LNPBP standards (I gave more info on this topic in my talk on The Lightning Conference this year).

It is possible that this statement was misinterpreted:

> This set of specifications covers standards & best practices for Layer 2, 3 solutions (and above) in cases when they do not require soft- or hard-forks on the Bitcoin blockchain level and are not directly related to issues covered in Lightning Network RFCs (BOLTs).

This does no say  "the criteria for proposals is that they not be LNP or BP specifications"; what it says is that LNP/BP proposals can't require hard or soft forks at the Bitcoin protocol level and can't diverge from/contradict to BOLTs (while there certainly will be more formal spec proposals for many things which are already in BOLTs).
